<?xml version="1.0" encoding="UTF-8"?>
<definitions 
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://www.example.com/VirtualWallet"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.example.com/VirtualWallet"
  name="VirtualWallet">

  <!-- Definición de mensajes -->
  <message name="RegisterCustomerRequest">
    <part name="documentNumber" type="xsd:string"/>
    <part name="name" type="xsd:string"/>
    <part name="email" type="xsd:string"/>
    <part name="phoneNumber" type="xsd:string"/>
  </message>

  <message name="RegisterCustomerResponse">
    <part name="success" type="xsd:boolean"/>
    <part name="cod_error" type="xsd:string"/>
    <part name="message_error" type="xsd:string"/>
    <part name="data" type="xsd:string"/>
  </message>

  <!-- Definición de operaciones -->
  <portType name="CustomerServicePortType">
    <operation name="registerCustomer">
      <input message="tns:RegisterCustomerRequest"/>
      <output message="tns:RegisterCustomerResponse"/>
    </operation>
  </portType>

  <!-- Definición de enlace (binding) -->
  <binding name="CustomerServiceBinding" type="tns:CustomerServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="registerCustomer">
      <soap:operation soapAction="http://www.example.com/VirtualWallet#RegisterCustomer"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <!-- Definición del servicio -->
  <service name="CustomerService">
    <port name="CustomerServicePort" binding="tns:CustomerServiceBinding">
      <soap:address location="http://localhost:3000/customers"/>
    </port>
  </service>
</definitions>
